//Represents the suit of a card.  The value represents the relative weight since we use suit as a tiebreaker when ordering the hand.  For example a 
//Queen of hearts is less than a queen of diamaonds since hearts has a value of 1 and diamonds has a value of 2.
enum Suit {
	Hearts = 1,
	Diamonds = 2,
	Clubs = 3,
	Spades = 4
}

//Represents a playing card.  Has a suit and a rank.  The rank is a number between 1 and 13, where 1 is an ace, 11 is a jack, 12 is a queen, and 13 is a king.  The suit is represented by the Suit enum.
export class Card {
	constructor(public suit: Suit, public rank: number) {
		this.suit = suit;
		this.rank = rank;
	}
	//getImage()
	//@description: This function returns the image path for the card in the assets directory.  The image is named in the format "rank_of_suit.png", where rank is the rank of the card and suit is the suit of the card.  For example, the image for the ace of hearts would be "ace_of_hearts.png".
	//@params: none
	//@returns: string - the image path for the card in the assets directory.
	getImage(): string {
	    const suitNames = ["hearts", "diamonds", "clubs", "spades"];
    	const rankNames = [null, "ace", "2", "3", "4", "5", "6", "7", "8", "9", "10", "jack", "queen", "king"];
		return `assets/images/${rankNames[this.rank]}_of_${suitNames[this.suit - 1]}.png`;
	}
}

//Represents a hand of 5 cards.  The hand is generated randomly and then ordered according to the rules of the game.  The ordering is done by first finding the two cards that are the same suit, then ordering those two cards by rank, then ordering the remaining three cards by rank and suit.  Finally, the hand is ordered according to the difference in rank between the two paired cards.  The possible orderings are:
//sml: small, medium, large
//slm: small, large, medium
//msl: medium, small, large
//mls: medium, large, small
//lsm: large, small, medium
//lms: large, medium, small
export class Hand {
	cards: Card[] = [];
	constructor() {
		this.cards = Hand.getRandomHand();
		console.log(this.cards);
		this.orderHand();
		console.log(this.cards);
	}

	//orderHand()
	//@description: This function orders the hand according to the rules of the game.  The ordering is done by first finding the two cards that are the same suit, then ordering those two cards by rank, then ordering the remaining three cards by rank and suit.  Finally, the hand is ordered according to the difference in rank between the two paired cards then encoding it in the order of the other cards,
	//@params: none
	//@returns: void
	public orderHand():void{
		// Pick 2 cards from hand that are the same suit
		const suitGroups: { [key: number]: Card[] } = {};
		this.cards.forEach(card => {
			if (!suitGroups[card.suit]) {
				suitGroups[card.suit] = [];
			}
			suitGroups[card.suit].push(card);
		});
		let suit:Suit=1;
		Object.keys(suitGroups).forEach(key => {
			const group = suitGroups[parseInt(key)];
			if (group.length >= 2) {
				suit=key as unknown as Suit;
			}
		});
		let paired:Card[]=[];		
		for (let i=0;i<2;i++){
			paired.push(suitGroups[suit][i]);
			this.cards.splice(this.cards.indexOf(suitGroups[suit][i]),1);
		}
		console.log(paired);
		paired.sort((a,b)=>a.rank-b.rank);
		let diff=paired[1].rank-paired[0].rank;
		//if diff>6 swap the cards
		if (diff>6){
			const temp=paired[0];
			paired[0]=paired[1];
			paired[1]=temp;
		}
		diff=paired[1].rank-paired[0].rank;
		//if diff is negative figure out the difference with wrap around
		if (diff<0){
			diff=paired[1].rank+13-paired[0].rank;
		}
		console.log("diff: "+diff);
		//sort cards by rank, then suit
		this.cards.sort((a,b)=>{
			if (a.rank===b.rank){
				return a.suit-b.suit;
			}
			return a.rank-b.rank;
		});
		switch(diff){
			case 1: //sml
				break;
			case 2: //slm
				this.swapCards(1,2)
				break;
			case 3:  //msl
				this.swapCards(0,1);
				break;
			case 4: //mls
				this.swapCards(0,2)
				this.swapCards(0,1);
				break;
			case 5: //lsm
				this.cards.unshift(this.cards.pop()!);
				break;
			case 6: //lms
				this.cards.reverse();
				break;
		}
		this.cards.unshift(paired[0]);
		this.cards.push(paired[1]);
	}

	//swapCards()
	//@description: This function swaps the cards at the given indices in the hand.
	//@params: 	index1: number - the index of the first card to swap, 
	// 			index2: number - the index of the second card to swap.
	//@returns: void
	//@private
	private swapCards(index1: number, index2: number): void {
		const temp = this.cards[index1];
		this.cards[index1] = this.cards[index2];
		this.cards[index2] = temp;
	}

	//getRandomHand()
	//@description: This function generates a random hand of 5 cards.  The hand is generated by randomly selecting a suit and rank for each card, and then checking for duplicates to ensure that the hand does not contain any duplicate cards.
	//@params: none
	//@returns: Card[] - an array of 5 unique Card objects representing the hand.
	private static getRandomHand(): Card[] {
		const hand: Card[] = [];
		while (hand.length < 5) {
			const suit = Math.floor(Math.random() * 4) + 1; // Random suit between 1 and 4
			const rank = Math.floor(Math.random() * 13) + 1; // Random rank between 1 and 13
			const card = new Card(suit, rank);
			// Check for duplicates
			if (!hand.some(c => c.suit === card.suit && c.rank === card.rank)) {
				hand.push(card);
			}
		}
		return hand;
	}

}