import { AfterViewInit, Component, Input, QueryList, ViewChildren } from '@angular/core';
import { Card, CardData, Suit } from "../card/card";

@Component({
  selector: 'app-hand',
  imports: [Card],
  templateUrl: './hand.html',
  styleUrl: './hand.scss',
})
export class Hand {
  @Input() show: boolean = false;
  @ViewChildren(Card) cards!: QueryList<Card>;

  cardData!: CardData[];

  constructor() {
    this.dealHand();
  }

  
  //dealHand()
  //@description: This function generates a random hand of 5 cards.  The hand is generated by randomly selecting a suit and rank for each card, and then checking for duplicates to ensure that the hand does not contain any duplicate cards.
  //@params: none
  //@returns: none
  //@side-effects: Updates the cards in the hand with a new random hand of 5 cards.
  public dealHand(): void {
    this.cardData = [];
    while (this.cardData.length < 5) {
      const suit = Math.floor(Math.random() * 4) + 1; // Random suit between 1 and 4
      const rank = Math.floor(Math.random() * 13) + 1; // Random rank between 1 and 13
      // Check for duplicates
      const card = { rank: rank, suit: suit };
      if (!this.cardData.some(c => c.suit === card.suit && c.rank === card.rank)) {
        this.cardData.push(card);
      }
    }
    this.orderHand();
    this.show = false;
  }

  //orderHand()
  //@description: This function orders the hand according to the rules of the game.  The ordering is done by first finding the two cards that are the same suit, then ordering those two cards by rank, then ordering the remaining three cards by rank and suit.  Finally, the hand is ordered according to the difference in rank between the two paired cards then encoding it in the order of the other cards,
  //@params: None
  //@returns: void
  //@side-effects: Updates the order of the cards in the hand according to the rules of the game.
  public orderHand(): void {
    // Pick 2 cards from hand that are the same suit
    const suitGroups: { [key: number]: CardData[] } = {};
    this.cardData.forEach(card => {
      if (!suitGroups[card.suit]) {
        suitGroups[card.suit] = [];
      }
      suitGroups[card.suit].push(card);
    });
    let suit: Suit = 1;
    Object.keys(suitGroups).forEach(key => {
      const group = suitGroups[parseInt(key)];
      if (group.length >= 2) {
        suit = key as unknown as Suit;
      }
    });
    let paired: CardData[] = [];
    for (let i = 0; i < 2; i++) {
      paired.push(suitGroups[suit][i]);
      this.cardData.splice(this.cardData.indexOf(suitGroups[suit][i]), 1);
    }
    paired.sort((a, b) => a.rank - b.rank);
    let diff = paired[1].rank - paired[0].rank;
    //if diff>6 swap the cards
    if (diff > 6) {
      let temp=paired[0];
      paired[0]=paired[1];
      paired[1]=temp;
    }
    diff = paired[1].rank - paired[0].rank;
    //if diff is negative figure out the difference with wrap around
    if (diff < 0) {
      diff = paired[1].rank + 13 - paired[0].rank;
    }
    
    //sort cards by rank, then suit
    this.cardData.sort((a, b) => {
      if (a.rank === b.rank) {
        return a.suit - b.suit;
      }
      return a.rank - b.rank;
    });
    switch (diff) {
      case 1: //sml
        break;
      case 2: //slm
        this.swapCards(1, 2)
        break;
      case 3:  //msl
        this.swapCards(0, 1);
        break;
      case 4: //mls
        this.swapCards(0, 2)
        this.swapCards(0, 1);
        break;
      case 5: //lsm
        this.cardData.unshift(this.cardData.pop()!);
        break;
      case 6: //lms
        this.cardData.reverse();
        break;
    }
    this.cardData.unshift(paired[0]);
    this.cardData.push(paired[1]);
  }

  //swapCards()
  //@description: This function swaps the cards at the given indices in the hand.
  //@params: 	index1: number - the index of the first card to swap, 
  // 			index2: number - the index of the second card to swap.
  //@returns: void
  //@private
  private swapCards(index1: number, index2: number): void {
    const temp:CardData = this.cardData[index1];
    this.cardData[index1] = this.cardData[index2];
    this.cardData[index2] = temp;
  }

}
